---
config: 
  layout: elk
---
stateDiagram-v2
  state "SEARCHING" as SEARCHING
  state "TRAVELLING" as TRAVELLING
 
  SEARCHING --> TRAVELLING : !obstacleInFront 
  SEARCHING --> SEARCHING: obstacleInFront
  TRAVELLING --> SEARCHING: obstacleInFront
  TRAVELLING --> TRAVELLING: !obstacleInFront
